name: CI

on:
  push:
    paths:
      - '**.zig'
      - '**/ci.yml'
  pull_request:
    paths:
      - '**.zig'
      - '**/ci.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        version: [0.11.0, '']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Install Dependencies
        run: |
          if [[ $RUNNER_OS == "Linux" ]]; then
            sudo apt install libglfw3-dev libepoxy-dev
          else
            brew install glfw libepoxy
            # find /usr/local/Cellar/glfw
            ln -s /usr/local/Cellar/glfw/3.4/lib/libglfw.dylib /usr/local/Cellar/libepoxy/1.5.10/lib/libglfw.dylib
            ln -s /usr/local/Cellar/glfw/3.4/include/GLFW /usr/local/Cellar/libepoxy/1.5.10/include/GLFW
            # find /usr/local/Cellar/libepoxy
          fi
      - uses: actions/checkout@v4
      - name: Build
        run: zig build
